version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=your_secret_key
